server:
  port: 9986

spring:
  datasource:
    url: jdbc:mysql://139.199.36.234:3306/cubic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: passw0rd
    driver-class-name: com.mysql.jdbc.Driver
  security:
    basic:
      enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cubic.model
  configuration:
    map-underscore-to-camel-case: true