server:
  port: 9986

spring:
  datasource:
    url: jdbc:mysql://192.168.1.234:3306/cubic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ;Zi;)r3bq(ss,;ds
    driver-class-name: com.mysql.jdbc.Driver
  security:
    basic:
      enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cubic.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log4j2.xml
